// ============================================================
// NETWORTH — Game Data (Jobs, Education, Businesses, Properties, etc.)
// ============================================================

import { Job, Education, BusinessTemplate, PropertyTemplate, LifestyleChoice, Achievement } from './types';

// ========================
// JOBS
// ========================

export const JOBS: Job[] = [
  // --- ENTRY LEVEL ---
  {
    id: 'delivery_driver',
    title: 'Delivery Driver',
    tier: 'entry',
    salary: 15000,
    stressLevel: 40,
    workHours: 48,
    experienceGain: 1,
    requirements: { education: [], skills: {}, experience: 0 },
    promotionChance: 0.1,
    description: 'Deliver packages across the city. Flexible hours, decent pay.',
    icon: 'Truck',
  },
  {
    id: 'waiter',
    title: 'Waiter',
    tier: 'entry',
    salary: 12000,
    stressLevel: 50,
    workHours: 44,
    experienceGain: 1,
    requirements: { education: [], skills: {}, experience: 0 },
    promotionChance: 0.08,
    description: 'Serve food at a restaurant. Tips can boost income.',
    icon: 'UtensilsCrossed',
  },
  {
    id: 'cashier',
    title: 'Cashier',
    tier: 'entry',
    salary: 13000,
    stressLevel: 35,
    workHours: 40,
    experienceGain: 1,
    requirements: { education: [], skills: {}, experience: 0 },
    promotionChance: 0.1,
    description: 'Handle transactions at a retail store. Steady work.',
    icon: 'ShoppingCart',
  },
  {
    id: 'warehouse_worker',
    title: 'Warehouse Worker',
    tier: 'entry',
    salary: 14000,
    stressLevel: 55,
    workHours: 50,
    experienceGain: 1,
    requirements: { education: [], skills: {}, experience: 0 },
    promotionChance: 0.08,
    description: 'Physical labor in a warehouse. Tough but honest work.',
    icon: 'Package',
  },
  {
    id: 'office_assistant',
    title: 'Office Assistant',
    tier: 'entry',
    salary: 16000,
    stressLevel: 30,
    workHours: 40,
    experienceGain: 1,
    requirements: { education: [], skills: { communication: 1 }, experience: 0 },
    promotionChance: 0.15,
    description: 'Administrative work in an office. Gateway to corporate life.',
    icon: 'FileText',
  },
  {
    id: 'data_entry',
    title: 'Data Entry Clerk',
    tier: 'entry',
    salary: 15000,
    stressLevel: 25,
    workHours: 40,
    experienceGain: 1,
    requirements: { education: [], skills: { technical: 1 }, experience: 0 },
    promotionChance: 0.12,
    description: 'Repetitive but easy. A stepping stone to analytics.',
    icon: 'Keyboard',
  },

  // --- MID LEVEL ---
  {
    id: 'software_engineer',
    title: 'Software Engineer',
    tier: 'mid',
    salary: 55000,
    stressLevel: 55,
    workHours: 45,
    experienceGain: 2,
    requirements: { education: ['cs_degree'], skills: { technical: 3 }, experience: 6 },
    promotionChance: 0.2,
    nextJobId: 'senior_engineer',
    description: 'Build software products. High pay, high demand.',
    icon: 'Code',
  },
  {
    id: 'accountant',
    title: 'Accountant',
    tier: 'mid',
    salary: 45000,
    stressLevel: 45,
    workHours: 42,
    experienceGain: 2,
    requirements: { education: ['commerce_degree'], skills: { finance: 2 }, experience: 6 },
    promotionChance: 0.15,
    description: 'Manage financial records. Stable career path.',
    icon: 'Calculator',
  },
  {
    id: 'marketing_manager',
    title: 'Marketing Manager',
    tier: 'mid',
    salary: 48000,
    stressLevel: 50,
    workHours: 44,
    experienceGain: 2,
    requirements: { education: ['marketing_cert'], skills: { marketing: 2, communication: 2 }, experience: 6 },
    promotionChance: 0.18,
    description: 'Lead marketing campaigns. Creative and strategic.',
    icon: 'Megaphone',
  },
  {
    id: 'data_analyst',
    title: 'Data Analyst',
    tier: 'mid',
    salary: 52000,
    stressLevel: 40,
    workHours: 42,
    experienceGain: 2,
    requirements: { education: ['analytics_cert'], skills: { analytics: 2, technical: 2 }, experience: 3 },
    promotionChance: 0.2,
    description: 'Turn data into insights. Growing field with great pay.',
    icon: 'BarChart3',
  },
  {
    id: 'designer',
    title: 'UI/UX Designer',
    tier: 'mid',
    salary: 46000,
    stressLevel: 35,
    workHours: 40,
    experienceGain: 2,
    requirements: { education: ['design_cert'], skills: { technical: 1, communication: 2 }, experience: 3 },
    promotionChance: 0.15,
    description: 'Design beautiful digital experiences.',
    icon: 'Palette',
  },
  {
    id: 'senior_engineer',
    title: 'Senior Software Engineer',
    tier: 'mid',
    salary: 90000,
    stressLevel: 60,
    workHours: 48,
    experienceGain: 3,
    requirements: { education: ['cs_degree'], skills: { technical: 5, leadership: 2 }, experience: 24 },
    promotionChance: 0.15,
    nextJobId: 'tech_lead',
    description: 'Lead technical decisions. Mentor junior engineers.',
    icon: 'Code',
  },

  // --- HIGH LEVEL ---
  {
    id: 'tech_lead',
    title: 'Tech Lead / CTO',
    tier: 'high',
    salary: 180000,
    stressLevel: 75,
    workHours: 55,
    experienceGain: 4,
    requirements: { education: ['cs_degree', 'mba'], skills: { technical: 7, leadership: 5 }, experience: 48 },
    promotionChance: 0.08,
    description: 'Lead entire engineering teams. Shape technology vision.',
    icon: 'Crown',
  },
  {
    id: 'business_director',
    title: 'Business Director',
    tier: 'high',
    salary: 200000,
    stressLevel: 70,
    workHours: 50,
    experienceGain: 4,
    requirements: { education: ['mba'], skills: { business: 6, leadership: 5, communication: 4 }, experience: 60 },
    promotionChance: 0.05,
    description: 'Direct business strategy. Shape company direction.',
    icon: 'Building2',
  },
  {
    id: 'investment_banker',
    title: 'Investment Banker',
    tier: 'high',
    salary: 250000,
    stressLevel: 90,
    workHours: 70,
    experienceGain: 5,
    requirements: { education: ['mba', 'trading_cert'], skills: { finance: 7, analytics: 5 }, experience: 36 },
    promotionChance: 0.05,
    description: 'High-stakes financial deals. Extreme stress, extreme pay.',
    icon: 'TrendingUp',
  },
  {
    id: 'startup_founder',
    title: 'Startup Founder',
    tier: 'high',
    salary: 50000, // Variable — boosted by business income
    stressLevel: 85,
    workHours: 60,
    experienceGain: 5,
    requirements: { education: [], skills: { business: 4, leadership: 3 }, experience: 12, creditScore: 600 },
    promotionChance: 0,
    description: 'Build your own tech startup. Risky but potentially massive returns.',
    icon: 'Rocket',
  },
];

// ========================
// EDUCATION
// ========================

export const EDUCATION_COURSES: Education[] = [
  // --- TIER 1: COURSES ---
  {
    id: 'basic_computer',
    name: 'Basic Computer Skills',
    tier: 'course',
    cost: 5000,
    costPerMonth: 2500,
    duration: 2,
    skillBoosts: { technical: 2 },
    salaryMultiplier: 1.05,
    unlocksJobs: [],
    prerequisites: [],
    description: 'Learn the basics of computing. Foundation for tech careers.',
    icon: 'Monitor',
  },
  {
    id: 'communication_course',
    name: 'Communication Skills',
    tier: 'course',
    cost: 4000,
    costPerMonth: 2000,
    duration: 2,
    skillBoosts: { communication: 2 },
    salaryMultiplier: 1.05,
    unlocksJobs: [],
    prerequisites: [],
    description: 'Improve your speaking and writing skills.',
    icon: 'MessageSquare',
  },
  {
    id: 'analytics_cert',
    name: 'Data Analytics Certification',
    tier: 'course',
    cost: 12000,
    costPerMonth: 4000,
    duration: 3,
    skillBoosts: { analytics: 3, technical: 1 },
    salaryMultiplier: 1.15,
    unlocksJobs: ['data_analyst'],
    prerequisites: ['basic_computer'],
    description: 'Google-certified data analytics program.',
    icon: 'PieChart',
  },
  {
    id: 'marketing_cert',
    name: 'Digital Marketing Certificate',
    tier: 'course',
    cost: 8000,
    costPerMonth: 4000,
    duration: 2,
    skillBoosts: { marketing: 3 },
    salaryMultiplier: 1.1,
    unlocksJobs: ['marketing_manager'],
    prerequisites: [],
    description: 'Learn SEO, social media, and digital advertising.',
    icon: 'Megaphone',
  },
  {
    id: 'design_cert',
    name: 'UI/UX Design Bootcamp',
    tier: 'course',
    cost: 15000,
    costPerMonth: 5000,
    duration: 3,
    skillBoosts: { technical: 2, communication: 1 },
    salaryMultiplier: 1.12,
    unlocksJobs: ['designer'],
    prerequisites: [],
    description: 'Design user interfaces and experiences.',
    icon: 'Palette',
  },
  {
    id: 'leadership_course',
    name: 'Leadership & Management',
    tier: 'course',
    cost: 10000,
    costPerMonth: 5000,
    duration: 2,
    skillBoosts: { leadership: 2, communication: 1 },
    salaryMultiplier: 1.08,
    unlocksJobs: [],
    prerequisites: [],
    description: 'Develop management and leadership abilities.',
    icon: 'Users',
  },

  // --- TIER 2: DEGREES ---
  {
    id: 'cs_degree',
    name: "Bachelor's in Computer Science",
    tier: 'degree',
    cost: 120000,
    costPerMonth: 10000,
    duration: 12,
    skillBoosts: { technical: 5, analytics: 2 },
    salaryMultiplier: 1.3,
    unlocksJobs: ['software_engineer', 'senior_engineer'],
    prerequisites: ['basic_computer'],
    description: 'Full CS degree. Gateway to high-paying tech jobs.',
    icon: 'GraduationCap',
  },
  {
    id: 'commerce_degree',
    name: "Bachelor's in Commerce",
    tier: 'degree',
    cost: 80000,
    costPerMonth: 6667,
    duration: 12,
    skillBoosts: { finance: 4, business: 2 },
    salaryMultiplier: 1.25,
    unlocksJobs: ['accountant'],
    prerequisites: [],
    description: 'Business and accounting fundamentals.',
    icon: 'GraduationCap',
  },
  {
    id: 'finance_cert',
    name: 'Financial Planning Certification',
    tier: 'degree',
    cost: 60000,
    costPerMonth: 10000,
    duration: 6,
    skillBoosts: { finance: 4 },
    salaryMultiplier: 1.2,
    unlocksJobs: [],
    prerequisites: [],
    description: 'Certified financial planner. Better investment returns.',
    icon: 'Wallet',
  },

  // --- TIER 3: ELITE ---
  {
    id: 'mba',
    name: 'MBA Program',
    tier: 'elite',
    cost: 300000,
    costPerMonth: 16667,
    duration: 18,
    skillBoosts: { business: 5, leadership: 4, finance: 3, communication: 2 },
    salaryMultiplier: 1.5,
    unlocksJobs: ['tech_lead', 'business_director'],
    prerequisites: ['cs_degree'],
    description: 'Master of Business Administration. Unlock CEO track.',
    icon: 'Award',
  },
  {
    id: 'ai_specialization',
    name: 'AI/ML Specialization',
    tier: 'elite',
    cost: 150000,
    costPerMonth: 25000,
    duration: 6,
    skillBoosts: { technical: 6, analytics: 4 },
    salaryMultiplier: 1.4,
    unlocksJobs: [],
    prerequisites: ['cs_degree'],
    description: 'Cutting-edge AI and machine learning. Premium salary boost.',
    icon: 'Brain',
  },
  {
    id: 'trading_cert',
    name: 'Trading License & Certification',
    tier: 'elite',
    cost: 100000,
    costPerMonth: 16667,
    duration: 6,
    skillBoosts: { finance: 5, analytics: 3 },
    salaryMultiplier: 1.35,
    unlocksJobs: ['investment_banker'],
    prerequisites: ['finance_cert'],
    description: 'Professional trading license. Unlock options & futures.',
    icon: 'LineChart',
  },
];

// ========================
// BUSINESSES
// ========================

export const BUSINESS_TEMPLATES: BusinessTemplate[] = [
  // --- SOLO ---
  {
    id: 'tea_stall',
    name: 'Tea Stall',
    tier: 'solo',
    startupCost: 50000,
    monthlyRevenue: 12000,
    monthlyExpenses: 7000,
    description: 'A simple roadside tea stall. Low investment, reliable income.',
    requirements: { cash: 50000 },
    upgrades: [
      { id: 'better_equipment', name: 'Premium Equipment', cost: 15000, revenueBoost: 1.2, expenseReduction: 1, description: 'Better machines, faster service' },
      { id: 'menu_expansion', name: 'Expand Menu', cost: 10000, revenueBoost: 1.3, expenseReduction: 0.95, description: 'Add snacks and cold drinks' },
    ],
    maxLevel: 5,
    riskFactor: 0.1,
    icon: 'Coffee',
  },
  {
    id: 'food_cart',
    name: 'Street Food Cart',
    tier: 'solo',
    startupCost: 75000,
    monthlyRevenue: 16000,
    monthlyExpenses: 9000,
    description: 'Serve delicious street food. Quick ROI if location is right.',
    requirements: { cash: 75000 },
    upgrades: [
      { id: 'prime_location', name: 'Prime Location', cost: 20000, revenueBoost: 1.4, expenseReduction: 1, description: 'Move to high-traffic area' },
      { id: 'branding', name: 'Brand Identity', cost: 12000, revenueBoost: 1.2, expenseReduction: 1, description: 'Custom branding & signage' },
    ],
    maxLevel: 5,
    riskFactor: 0.15,
    icon: 'Utensils',
  },
  {
    id: 'repair_shop',
    name: 'Phone Repair Shop',
    tier: 'solo',
    startupCost: 200000,
    monthlyRevenue: 28000,
    monthlyExpenses: 13000,
    description: 'Fix phones and electronics. Growing demand everywhere.',
    requirements: { cash: 200000, skills: { technical: 2 } },
    upgrades: [
      { id: 'tools', name: 'Advanced Tools', cost: 30000, revenueBoost: 1.3, expenseReduction: 0.9, description: 'Handle complex repairs' },
      { id: 'hire_tech', name: 'Hire Technician', cost: 15000, revenueBoost: 1.5, expenseReduction: 0.85, description: 'Scale with more hands' },
    ],
    maxLevel: 5,
    riskFactor: 0.12,
    icon: 'Wrench',
  },
  {
    id: 'delivery_gig',
    name: 'Delivery Fleet',
    tier: 'solo',
    startupCost: 60000,
    monthlyRevenue: 14000,
    monthlyExpenses: 6000,
    description: 'Start with one bike, grow to a fleet. Scalable.',
    requirements: { cash: 60000 },
    upgrades: [
      { id: 'extra_bike', name: 'Add Vehicle', cost: 40000, revenueBoost: 1.6, expenseReduction: 0.8, description: 'More vehicles, more deliveries' },
      { id: 'app_integration', name: 'App Integration', cost: 25000, revenueBoost: 1.3, expenseReduction: 1, description: 'Partner with delivery apps' },
    ],
    maxLevel: 5,
    riskFactor: 0.15,
    icon: 'Bike',
  },

  // --- SMALL ---
  {
    id: 'coffee_shop',
    name: 'Coffee Shop',
    tier: 'small',
    startupCost: 500000,
    monthlyRevenue: 55000,
    monthlyExpenses: 28000,
    description: 'Trendy coffee shop. Great margins with right location.',
    requirements: { cash: 500000, reputation: 20 },
    upgrades: [
      { id: 'ambiance', name: 'Premium Ambiance', cost: 80000, revenueBoost: 1.3, expenseReduction: 1, description: 'Aesthetic upgrade → more customers' },
      { id: 'wifi_cowork', name: 'Co-working Space', cost: 50000, revenueBoost: 1.4, expenseReduction: 0.95, description: 'Attract remote workers' },
      { id: 'franchise_prep', name: 'Franchise Model', cost: 150000, revenueBoost: 2.0, expenseReduction: 0.7, description: 'Prepare for franchising' },
    ],
    maxLevel: 8,
    riskFactor: 0.2,
    icon: 'Coffee',
  },
  {
    id: 'fitness_studio',
    name: 'Fitness Studio',
    tier: 'small',
    startupCost: 1500000,
    monthlyRevenue: 80000,
    monthlyExpenses: 45000,
    description: 'Modern fitness studio. Recurring membership model.',
    requirements: { cash: 1500000, reputation: 30 },
    upgrades: [
      { id: 'equipment', name: 'Premium Equipment', cost: 200000, revenueBoost: 1.3, expenseReduction: 1, description: 'Top-tier machines' },
      { id: 'trainers', name: 'Personal Trainers', cost: 100000, revenueBoost: 1.5, expenseReduction: 0.85, description: 'Premium training services' },
    ],
    maxLevel: 8,
    riskFactor: 0.25,
    icon: 'Dumbbell',
  },
  {
    id: 'online_store',
    name: 'E-Commerce Store',
    tier: 'small',
    startupCost: 300000,
    monthlyRevenue: 45000,
    monthlyExpenses: 18000,
    description: 'Online store. Low overhead, scalable. Passive income.',
    requirements: { cash: 300000, skills: { technical: 2, marketing: 2 } },
    upgrades: [
      { id: 'ads', name: 'Paid Advertising', cost: 50000, revenueBoost: 1.5, expenseReduction: 0.8, description: 'Scale with ads' },
      { id: 'automation', name: 'Fulfillment Automation', cost: 100000, revenueBoost: 1.2, expenseReduction: 1.2, description: 'Automate shipping' },
    ],
    maxLevel: 8,
    riskFactor: 0.2,
    icon: 'ShoppingBag',
  },

  // --- MAJOR ---
  {
    id: 'restaurant_chain',
    name: 'Restaurant Chain',
    tier: 'major',
    startupCost: 5000000,
    monthlyRevenue: 250000,
    monthlyExpenses: 120000,
    description: 'Multi-location restaurant business. High revenue, high complexity.',
    requirements: { cash: 5000000, reputation: 50, skills: { business: 4, leadership: 3 } },
    upgrades: [
      { id: 'new_location', name: 'Open New Location', cost: 2000000, revenueBoost: 1.6, expenseReduction: 0.75, description: 'Expand to new cities' },
      { id: 'central_kitchen', name: 'Central Kitchen', cost: 1000000, revenueBoost: 1.1, expenseReduction: 1.3, description: 'Cut costs with centralized prep' },
    ],
    maxLevel: 10,
    riskFactor: 0.3,
    icon: 'ChefHat',
  },
  {
    id: 'tech_startup',
    name: 'Tech Startup',
    tier: 'major',
    startupCost: 2000000,
    monthlyRevenue: 150000,
    monthlyExpenses: 90000,
    description: 'Build the next big app. High risk, potentially massive returns.',
    requirements: { cash: 2000000, skills: { technical: 5, business: 3 }, education: ['cs_degree'] },
    upgrades: [
      { id: 'funding', name: 'Raise Funding', cost: 500000, revenueBoost: 2.0, expenseReduction: 0.6, description: 'VC funding for rapid growth' },
      { id: 'team', name: 'Expand Team', cost: 300000, revenueBoost: 1.5, expenseReduction: 0.8, description: 'Hire top talent' },
    ],
    maxLevel: 10,
    riskFactor: 0.4,
    icon: 'Rocket',
  },
  {
    id: 'ai_company',
    name: 'AI Solutions Company',
    tier: 'major',
    startupCost: 8000000,
    monthlyRevenue: 400000,
    monthlyExpenses: 200000,
    description: 'Enterprise AI solutions. Cutting edge tech, premium clients.',
    requirements: { cash: 8000000, skills: { technical: 7, business: 5 }, education: ['ai_specialization'] },
    upgrades: [
      { id: 'research', name: 'R&D Lab', cost: 2000000, revenueBoost: 1.8, expenseReduction: 0.7, description: 'Breakthrough research' },
      { id: 'enterprise', name: 'Enterprise Sales', cost: 1000000, revenueBoost: 1.5, expenseReduction: 0.9, description: 'Land Fortune 500 clients' },
    ],
    maxLevel: 10,
    riskFactor: 0.35,
    icon: 'Brain',
  },
  {
    id: 'real_estate_dev',
    name: 'Real Estate Development',
    tier: 'major',
    startupCost: 15000000,
    monthlyRevenue: 500000,
    monthlyExpenses: 280000,
    description: 'Develop residential & commercial properties. Massive capital required.',
    requirements: { cash: 15000000, reputation: 60, skills: { business: 6, finance: 5 } },
    upgrades: [
      { id: 'luxury', name: 'Luxury Segment', cost: 5000000, revenueBoost: 1.8, expenseReduction: 0.8, description: 'Premium luxury developments' },
      { id: 'commercial', name: 'Commercial Projects', cost: 3000000, revenueBoost: 1.5, expenseReduction: 0.85, description: 'Office spaces & malls' },
    ],
    maxLevel: 10,
    riskFactor: 0.3,
    icon: 'Building',
  },
];

// ========================
// PROPERTIES
// ========================

export const PROPERTY_TEMPLATES: PropertyTemplate[] = [
  // Housing (player lives here)
  {
    id: 'tiny_room',
    name: 'Tiny Rented Room',
    type: 'rental',
    purchasePrice: 0,
    monthlyRent: 5000,
    appreciation: 0,
    maintenanceCost: 0,
    propertyTax: 0,
    happinessBoost: -10,
    description: 'A cramped single room. Cheap but depressing.',
    requirements: {},
    icon: 'Home',
  },
  {
    id: 'one_bhk',
    name: '1BHK Apartment',
    type: 'rental',
    purchasePrice: 0,
    monthlyRent: 15000,
    appreciation: 0,
    maintenanceCost: 0,
    propertyTax: 0,
    happinessBoost: 5,
    description: 'A decent apartment. Comfortable enough.',
    requirements: {},
    icon: 'Home',
  },
  {
    id: 'two_bhk',
    name: '2BHK Apartment',
    type: 'rental',
    purchasePrice: 0,
    monthlyRent: 30000,
    appreciation: 0,
    maintenanceCost: 0,
    propertyTax: 0,
    happinessBoost: 15,
    description: 'Spacious living. Room for a home office.',
    requirements: {},
    icon: 'Home',
  },
  {
    id: 'luxury_apartment',
    name: 'Luxury Apartment',
    type: 'rental',
    purchasePrice: 0,
    monthlyRent: 80000,
    appreciation: 0,
    maintenanceCost: 0,
    propertyTax: 0,
    happinessBoost: 25,
    description: 'Premium living with amenities. Status symbol.',
    requirements: {},
    icon: 'Building2',
  },
  {
    id: 'penthouse',
    name: 'Penthouse Suite',
    type: 'rental',
    purchasePrice: 0,
    monthlyRent: 200000,
    appreciation: 0,
    maintenanceCost: 0,
    propertyTax: 0,
    happinessBoost: 40,
    description: 'The ultimate flex. Rooftop living.',
    requirements: {},
    icon: 'Crown',
  },

  // Investment properties
  {
    id: 'invest_1bhk',
    name: '1BHK Investment Property',
    type: 'investment',
    purchasePrice: 5000000,
    monthlyRent: 15000,
    appreciation: 0.05,
    maintenanceCost: 0.01,
    propertyTax: 0.005,
    happinessBoost: 0,
    description: 'Buy a 1BHK and rent it out. Steady rental income.',
    requirements: { cash: 1500000, creditScore: 650 },
    icon: 'Building',
  },
  {
    id: 'invest_apartment_building',
    name: 'Apartment Building',
    type: 'investment',
    purchasePrice: 20000000,
    monthlyRent: 80000,
    appreciation: 0.06,
    maintenanceCost: 0.01,
    propertyTax: 0.005,
    happinessBoost: 0,
    description: '4-unit apartment building. Multiple income streams.',
    requirements: { cash: 6000000, creditScore: 700 },
    icon: 'Building2',
  },
  {
    id: 'commercial_property',
    name: 'Commercial Office Space',
    type: 'commercial',
    purchasePrice: 50000000,
    monthlyRent: 250000,
    appreciation: 0.07,
    maintenanceCost: 0.008,
    propertyTax: 0.005,
    happinessBoost: 0,
    description: 'Prime commercial real estate. Rent to businesses.',
    requirements: { cash: 15000000, creditScore: 750, netWorth: 30000000 },
    icon: 'Landmark',
  },
];

// ========================
// LIFESTYLE CHOICES
// ========================

export const LIFESTYLE_CHOICES: LifestyleChoice[] = [
  {
    id: 'gym',
    name: 'Gym Membership',
    monthlyCost: 1500,
    effects: { health: 5, motivation: 3, happiness: 2 },
    description: 'Stay fit and energized.',
    icon: 'Dumbbell',
  },
  {
    id: 'therapy',
    name: 'Therapy Sessions',
    monthlyCost: 3000,
    effects: { happiness: 5, health: 2, motivation: 3 },
    description: 'Mental health matters. Reduce stress.',
    icon: 'Brain',
  },
  {
    id: 'hobbies',
    name: 'Hobbies & Interests',
    monthlyCost: 2000,
    effects: { happiness: 8, motivation: 2 },
    description: 'Photography, gaming, music — enjoy life.',
    icon: 'Gamepad2',
  },
  {
    id: 'dating',
    name: 'Social Life & Dating',
    monthlyCost: 5000,
    effects: { happiness: 12, motivation: 3, reputation: 2 },
    description: 'Go out, meet people, build relationships.',
    icon: 'Heart',
  },
  {
    id: 'networking',
    name: 'Professional Networking',
    monthlyCost: 3000,
    effects: { reputation: 8, motivation: 2 },
    description: 'Attend events, build connections.',
    icon: 'Users',
  },
  {
    id: 'meditation',
    name: 'Meditation & Yoga',
    monthlyCost: 500,
    effects: { health: 3, happiness: 4, motivation: 2 },
    description: 'Inner peace. Cheap and effective.',
    icon: 'Sparkles',
  },
];

// ========================
// ACHIEVEMENTS
// ========================

export const ACHIEVEMENTS: Achievement[] = [
  // Wealth milestones
  { id: 'first_lakh', title: 'First ₹1 Lakh', description: 'Reach ₹1,00,000 net worth', icon: '💰', reward: 10, category: 'wealth', condition: { type: 'netWorth', value: 100000 }, isUnlocked: false },
  { id: 'five_lakh', title: '₹5 Lakh Club', description: 'Reach ₹5,00,000 net worth', icon: '💎', reward: 25, category: 'wealth', condition: { type: 'netWorth', value: 500000 }, isUnlocked: false },
  { id: 'first_million', title: 'Millionaire!', description: 'Reach ₹10,00,000 net worth', icon: '🏆', reward: 50, category: 'wealth', condition: { type: 'netWorth', value: 1000000 }, isUnlocked: false },
  { id: 'fifty_lakh', title: '₹50 Lakh Baron', description: 'Reach ₹50,00,000 net worth', icon: '👑', reward: 75, category: 'wealth', condition: { type: 'netWorth', value: 5000000 }, isUnlocked: false },
  { id: 'crorepati', title: 'Crorepati!', description: 'Reach ₹1 Crore net worth', icon: '🌟', reward: 100, category: 'wealth', condition: { type: 'netWorth', value: 10000000 }, isUnlocked: false },
  { id: 'ten_crore', title: 'Mega Rich', description: 'Reach ₹10 Crore net worth', icon: '🔥', reward: 200, category: 'wealth', condition: { type: 'netWorth', value: 100000000 }, isUnlocked: false },
  { id: 'hundred_crore', title: 'Tycoon', description: 'Reach ₹100 Crore net worth', icon: '🏰', reward: 300, category: 'wealth', condition: { type: 'netWorth', value: 1000000000 }, isUnlocked: false },
  { id: 'billionaire', title: 'BILLIONAIRE', description: 'Reach ₹1,000 Crore net worth', icon: '🚀', reward: 500, category: 'wealth', condition: { type: 'netWorth', value: 10000000000 }, isUnlocked: false },

  // Business milestones
  { id: 'first_business', title: 'Entrepreneur', description: 'Own your first business', icon: '🏪', reward: 20, category: 'business', condition: { type: 'businesses', value: 1 }, isUnlocked: false },
  { id: 'three_businesses', title: 'Business Mogul', description: 'Own 3 businesses', icon: '🏢', reward: 50, category: 'business', condition: { type: 'businesses', value: 3 }, isUnlocked: false },
  { id: 'five_businesses', title: 'Empire Builder', description: 'Own 5 businesses', icon: '🌆', reward: 100, category: 'business', condition: { type: 'businesses', value: 5 }, isUnlocked: false },

  // Investment milestones
  { id: 'first_stock', title: 'Investor', description: 'Buy your first stock', icon: '📈', reward: 10, category: 'investment', condition: { type: 'stocks', value: 1 }, isUnlocked: false },
  { id: 'diversified', title: 'Diversified', description: 'Own stocks in 5+ companies', icon: '📊', reward: 50, category: 'investment', condition: { type: 'stocks', value: 5 }, isUnlocked: false },

  // Career milestones
  { id: 'first_promotion', title: 'Moving Up', description: 'Get your first promotion', icon: '⬆️', reward: 20, category: 'career', condition: { type: 'job', value: 1 }, isUnlocked: false },
  { id: 'mid_career', title: 'Mid-Level Pro', description: 'Land a mid-level job', icon: '💼', reward: 30, category: 'career', condition: { type: 'job', value: 2 }, isUnlocked: false },
  { id: 'executive', title: 'Executive', description: 'Reach a high-level position', icon: '👔', reward: 100, category: 'career', condition: { type: 'job', value: 3 }, isUnlocked: false },

  // Life milestones
  { id: 'debt_free', title: 'Debt Free!', description: 'Pay off all your debts', icon: '🎉', reward: 100, category: 'life', condition: { type: 'debtFree', value: 1 }, isUnlocked: false },
  { id: 'one_year', title: 'Year One', description: 'Play for 12 months', icon: '📅', reward: 30, category: 'life', condition: { type: 'monthsPlayed', value: 12 }, isUnlocked: false },
  { id: 'five_years', title: 'Veteran', description: 'Play for 60 months', icon: '🏅', reward: 100, category: 'life', condition: { type: 'monthsPlayed', value: 60 }, isUnlocked: false },
];
