// ============================================================
// NETWORTH — Side Hustle Data
// ============================================================

import { SideHustle } from './types';

export const SIDE_HUSTLES: SideHustle[] = [
  // --- Freelancing ---
  {
    id: 'freelance_webdev',
    name: 'Web Development',
    type: 'freelance',
    baseIncome: 15000,
    variability: 0.3,
    hoursPerWeek: 15,
    energyCost: 12,
    requirements: { skills: { technical: 3 } },
    growthRate: 0.03,
    description: 'Build websites and apps for clients. Income grows with portfolio.',
    icon: '💻',
  },
  {
    id: 'freelance_design',
    name: 'Graphic Design',
    type: 'freelance',
    baseIncome: 12000,
    variability: 0.25,
    hoursPerWeek: 12,
    energyCost: 8,
    requirements: { skills: { technical: 2, communication: 2 } },
    growthRate: 0.02,
    description: 'Create logos, banners, and brand materials for small businesses.',
    icon: '🎨',
  },
  {
    id: 'freelance_writing',
    name: 'Content Writing',
    type: 'freelance',
    baseIncome: 8000,
    variability: 0.2,
    hoursPerWeek: 10,
    energyCost: 5,
    requirements: { skills: { communication: 3 } },
    growthRate: 0.02,
    description: 'Write articles, blogs, and copy for businesses.',
    icon: '✍️',
  },
  // --- Content Creation ---
  {
    id: 'content_youtube',
    name: 'YouTube Channel',
    type: 'content',
    baseIncome: 2000,
    variability: 0.5,
    hoursPerWeek: 20,
    energyCost: 15,
    requirements: { skills: { communication: 3, technical: 1 } },
    growthRate: 0.08,
    description: 'Start a YouTube channel. Slow start, exponential growth potential.',
    icon: '📹',
  },
  {
    id: 'content_blog',
    name: 'Finance Blog',
    type: 'content',
    baseIncome: 1000,
    variability: 0.4,
    hoursPerWeek: 8,
    energyCost: 5,
    requirements: { skills: { finance: 2, communication: 2 } },
    growthRate: 0.06,
    description: 'Write about personal finance. Ad revenue grows with readership.',
    icon: '📝',
  },
  {
    id: 'content_podcast',
    name: 'Podcast',
    type: 'content',
    baseIncome: 1500,
    variability: 0.4,
    hoursPerWeek: 6,
    energyCost: 4,
    requirements: { skills: { communication: 4 } },
    growthRate: 0.05,
    description: 'Interview experts, build audience. Sponsorships come with scale.',
    icon: '🎙️',
  },
  // --- Gig Economy ---
  {
    id: 'gig_delivery',
    name: 'Food Delivery',
    type: 'gig',
    baseIncome: 10000,
    variability: 0.15,
    hoursPerWeek: 20,
    energyCost: 20,
    requirements: { skills: {} },
    growthRate: 0,
    description: 'Deliver food via apps. Immediate income, high physical cost.',
    icon: '🛵',
  },
  {
    id: 'gig_rideshare',
    name: 'Ride Sharing',
    type: 'gig',
    baseIncome: 18000,
    variability: 0.2,
    hoursPerWeek: 25,
    energyCost: 18,
    requirements: { skills: {} },
    growthRate: 0,
    description: 'Drive for ride-sharing apps. Requires vehicle. Good immediate income.',
    icon: '🚗',
  },
  {
    id: 'gig_tutoring',
    name: 'Online Tutoring',
    type: 'gig',
    baseIncome: 12000,
    variability: 0.2,
    hoursPerWeek: 10,
    energyCost: 8,
    requirements: { skills: { communication: 2 }, experience: 6 },
    growthRate: 0.02,
    description: 'Teach students online. Flexible hours, decent pay.',
    icon: '📚',
  },
  // --- Consulting ---
  {
    id: 'consulting_tech',
    name: 'Tech Consulting',
    type: 'consulting',
    baseIncome: 40000,
    variability: 0.3,
    hoursPerWeek: 10,
    energyCost: 10,
    requirements: { skills: { technical: 6, business: 3 }, reputation: 50, experience: 24 },
    growthRate: 0.04,
    description: 'Advise companies on tech strategy. Premium rates, needs strong reputation.',
    icon: '🏛️',
  },
  {
    id: 'consulting_finance',
    name: 'Financial Consulting',
    type: 'consulting',
    baseIncome: 50000,
    variability: 0.25,
    hoursPerWeek: 12,
    energyCost: 10,
    requirements: { skills: { finance: 6, analytics: 4 }, reputation: 60, experience: 36 },
    growthRate: 0.04,
    description: 'Advise on investments and financial planning. High-value clients.',
    icon: '📊',
  },
];
