// ============================================================
// NETWORTH — Stock Market Data
// ============================================================

import { Company, CryptoAsset } from './types';

export const COMPANIES: Omit<Company, 'currentPrice' | 'priceHistory'>[] = [
  {
    id: 'nexaai',
    name: 'NexaAI',
    ticker: 'NEXA',
    sector: 'tech',
    basePrice: 1200,
    volatility: 0.6,
    dividendYield: 0.01,
    growthTendency: 0.4,
    description: 'Leading AI infrastructure company. High growth, high volatility.',
    icon: 'Brain',
  },
  {
    id: 'voltmotors',
    name: 'Volt Motors',
    ticker: 'VOLT',
    sector: 'auto',
    basePrice: 850,
    volatility: 0.4,
    dividendYield: 0.02,
    growthTendency: 0.3,
    description: 'Electric vehicle manufacturer disrupting traditional auto.',
    icon: 'Car',
  },
  {
    id: 'quantumx',
    name: 'QuantumX',
    ticker: 'QNTX',
    sector: 'tech',
    basePrice: 3500,
    volatility: 0.7,
    dividendYield: 0.0,
    growthTendency: 0.5,
    description: 'Quantum computing pioneer. Extremely volatile, massive upside.',
    icon: 'Atom',
  },
  {
    id: 'greengrid',
    name: 'GreenGrid',
    ticker: 'GGRD',
    sector: 'green',
    basePrice: 420,
    volatility: 0.3,
    dividendYield: 0.04,
    growthTendency: 0.2,
    description: 'Renewable energy giant. Stable dividends, steady growth.',
    icon: 'Leaf',
  },
  {
    id: 'skynetmedia',
    name: 'SkyNet Media',
    ticker: 'SKYM',
    sector: 'media',
    basePrice: 280,
    volatility: 0.5,
    dividendYield: 0.03,
    growthTendency: 0.1,
    description: 'Streaming & social media conglomerate.',
    icon: 'Tv',
  },
  {
    id: 'biocore',
    name: 'BioCore',
    ticker: 'BIOC',
    sector: 'biotech',
    basePrice: 1800,
    volatility: 0.65,
    dividendYield: 0.01,
    growthTendency: 0.35,
    description: 'Biotech research firm. Breakthrough drugs or bust.',
    icon: 'Dna',
  },
  {
    id: 'cryptovault',
    name: 'CryptoVault',
    ticker: 'CVLT',
    sector: 'crypto',
    basePrice: 650,
    volatility: 0.8,
    dividendYield: 0.0,
    growthTendency: 0.2,
    description: 'Blockchain infrastructure and digital asset custody.',
    icon: 'Lock',
  },
  {
    id: 'healthtech',
    name: 'HealthTech',
    ticker: 'HTCH',
    sector: 'health',
    basePrice: 560,
    volatility: 0.25,
    dividendYield: 0.05,
    growthTendency: 0.15,
    description: 'Healthcare technology. Defensive stock with reliable dividends.',
    icon: 'Heart',
  },
  {
    id: 'spaceorbit',
    name: 'SpaceOrbit',
    ticker: 'SORB',
    sector: 'space',
    basePrice: 5200,
    volatility: 0.75,
    dividendYield: 0.0,
    growthTendency: 0.45,
    description: 'Space exploration & satellite internet. Moon shot or nothing.',
    icon: 'Rocket',
  },
  {
    id: 'finpay',
    name: 'FinPay',
    ticker: 'FNPY',
    sector: 'finance',
    basePrice: 320,
    volatility: 0.35,
    dividendYield: 0.06,
    growthTendency: 0.2,
    description: 'Digital payments & fintech. High dividend, stable growth.',
    icon: 'CreditCard',
  },
];

export const CRYPTO_ASSETS: Omit<CryptoAsset, 'currentPrice' | 'priceHistory'>[] = [
  {
    id: 'netcoin',
    name: 'NetCoin',
    ticker: 'NTC',
    volatility: 0.4,
    description: 'Stable crypto. Good entry point for crypto beginners.',
  },
  {
    id: 'volttoken',
    name: 'VoltToken',
    ticker: 'VTK',
    volatility: 0.9,
    description: 'Meme coin with extreme volatility. Gamble responsibly.',
  },
  {
    id: 'aichain',
    name: 'AI-Chain',
    ticker: 'AIC',
    volatility: 0.75,
    description: 'AI-powered blockchain. Surges during AI booms.',
  },
  {
    id: 'metagold',
    name: 'MetaGold',
    ticker: 'MGD',
    volatility: 0.95,
    description: 'Speculative digital gold. Extreme swings.',
  },
];

// Initial crypto prices
export const CRYPTO_BASE_PRICES: Record<string, number> = {
  netcoin: 150,
  volttoken: 25,
  aichain: 80,
  metagold: 500,
};
